feature: PR #11 코드 리뷰 반영
JNU-econovation/NomadNest_BE pull request #29
Opened 2024-10-30 16:24 UTC by Lee-Dahyeon

## ⚠️ 연관된 이슈 번호 #28 
- #28 
## 📋 작업 내용
- 코드 리뷰 반영하여 수정하였습니다.
  - 어노테이션 추가
  - 메소드명 수정
  - 예외 처리(orElseThrow)

## 📷 스크린샷(선택) 

## 💬 리뷰 요구사항
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
> e.g. 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-11-03 17:50 UTC, LJH098 requested changes
제가 놓쳤었는데
public interface ParticipantRepository extends JpaRepository<User, Long> {

이 부분 User가 아니라 Participant가 되야 할 것 같습니다.

2024-11-03 17:50 UTC, LJH098 commented on src/main/java/com/hyunsolution/dangu/participant/domain/ParticipantRepository.java
> +    Boolean isClickedById(long id);
`Boolean existsByIdAndAndParticipantMatchTrue(long id);
`
위처럼 JPQL을 사용하지 않고 Data JPA를 사용 할 수도 있을 것 같아요

그리고 isClicekd는 너무 추상적인 단어 인 것 같아요.

2024-11-03 17:50 UTC, LJH098 commented on src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
>                  .toList();
#27 PR이 아직 머지가 되지 않았는데 해당 PR의 commit이 그대로 있는 것 보아하니
feature-#28 브랜치를  develop에서 브랜치를 생성하는 것이 아니라 feature-#26에서 생성한 것 같은데 맞을까요??

2024-11-06 15:07 UTC, Lee-Dahyeon commented on src/main/java/com/hyunsolution/dangu/workspace/service/WorkspaceService.java
>                  .toList();
현재는 머지가 된 상태입니다!

2024-11-06 16:42 UTC, merged