feature: 매칭 현황 기능 구현 및 정책정의서 반영
JNU-econovation/NomadNest_BE pull request #64
Opened 2024-11-28 08:50 UTC by Lee-Dahyeon

## ⚠️ 연관된 이슈 번호 #62 
- close #62 

## 📋 작업 내용(수정하겠습니다!)
- 모든 테이블에 is-deleted컬럼 추가하여 soft delete 진행
- Chatting enum 칼럼 추가
- 매칭 신청에 따른 메시지 저장

## 📷 스크린샷(선택) 

## 💬 리뷰 요구사항
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
> e.g. 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-11-28 12:38 UTC, LJH098 requested changes

2024-11-28 12:38 UTC, LJH098 commented on src/main/java/com/hyunsolution/dangu/chatting/domain/Chatting.java
> +
MessageType은 왜 기본값 설정을 하신건가요?

2024-11-28 12:38 UTC, LJH098 commented on src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
> +        Long workspaceId = chatRoomRepository.findById(chatRoomId).orElseThrow(() -> ChatRoomNotFoundException.EXCEPTION).getWorkspace().getId();
...??!! 
chatRoomRepository.findById(chatRoomId).orElseThrow(() -> ChatRoomNotFoundException.EXCEPTION) 을 중복 작성하고 있습니다.

2024-11-28 12:38 UTC, LJH098 commented on src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
> +        String uid= participantRepository.findById(id).orElseThrow(() -> ParticipantNotFoundException.EXCEPTION).getUser().getUid();
예..? 여기서 id는 userId인데 participantRepository.findById(id)를 하신다구요..?!
findById를 하면 안될 뿐더러 단순히 uid를 찾는거면 userId로 user를 조회하는게 더 좋지않을까요?

2024-11-28 12:38 UTC, LJH098 commented on src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
> +        boolean myself = participantRepository.findById(userId).orElseThrow(() -> UserNotFoundException.EXCEPTION).isParticipantMatch();
... ㅜㅜ 왜자꾸 userId로 participantRepository.findById 하는거죠

2024-11-28 12:38 UTC, LJH098 commented on src/main/java/com/hyunsolution/dangu/participant/service/ParticipantService.java
> +        }
.... 왜 participant의 pk와 user pk랑 비교하나요..

2024-11-29 12:31 UTC, Lee-Dahyeon commented on src/main/java/com/hyunsolution/dangu/chatting/domain/Chatting.java
> +
기본값을 설정하여 다른 코드에서 default값인 TEXT인 경우는 삭제하였습니다!

2024-11-29 12:36 UTC, merged